name: Release Mistral OCR Plugin

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Create release package
        run: |
          mkdir -p release/MistralOCR
          cp -r MistralOCR/* release/MistralOCR/
          cd release
          zip -r mistral-ocr-plugin.zip MistralOCR

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: Mistral OCR Plugin v${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
          files: release/mistral-ocr-plugin.zip
          body: |
            # Mistral OCR Plugin v${{ steps.get_version.outputs.VERSION }}
            
            ## 安装方法 (Installation)
            
            1. 下载 `mistral-ocr-plugin.zip`
            2. 解压缩到 Umi-OCR 插件目录
            3. 重启 Umi-OCR
            4. 在设置中启用 Mistral OCR 插件
            

